=== Description de l’état de l’art
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]

Nous avons dégagé deux types d'applications : celles qui calculent un bilan carbone et d'autres qui proposent des alternatives ou qui récompensent les utilisateurs suivant leurs achats. Pour ce qui est des applications qui calculent le bilan carbone (Earth Hero, Klima), elles se fondent uniquement sur les quelques réponses que donnent les utilisateurs (pays de résidence, type de régime alimentaire, fréquence de vols en avion et type de logement) et calculent ensuite le bilan à partir de moyennes. Non seulement le résultat n'est que peu personnalisé, mais en plus il diffère d'une application à l'autre, parfois du simple au double pour les mêmes questions...


Ainsi, l'ambition de notre application est de calculer un bilan précis et le plus fiable possible. Notre application devra tout de même, pour certains paramètres, se baser sur des moyennes. En effet, il nous sera impossible d'estimer de manière précise la consommation ménagère de notre utilisateur. Deuxièmement, nous avons remarqué que les applications proposaient des actions concrètes (participer à des projets, s'informer sur les enjeux et les solutions, etc.). En contrepartie, l'utilisateur peut recevoir des points et/ou des récompenses (Ex : bon d'achat). Hormis l'aspect moralisateur du dernier point évoqué, elles demandent un véritable engagement de la part de l’utilisateur. De plus, encore une fois, les solutions proposées sont très générales et ne prennent pas en compte réellement les habitudes de l’utilisateur. Notre ambition est donc de proposer des alternatives personnalisées et adaptées aux capacités (financières, physiques ou morales) de l’utilisateur. Ces alternatives relèveraient toujours de l’engagement, mais seraient bien plus simples à mettre en place et ne perturberaient pas le train de vie de notre utilisateur.
